### ISSUE TITLE
From Ian: geographical organisation for dashboard 

### ISSUE THREAD

**Issue by gjhltn** [tpximpact/mhclg-oruk#14]
From [Ian on slack ](https://tpximpact.slack.com/archives/C06LN6GKCAE/p1726655259562219?thread_ts=1726650810.934539&channel=C06LN6GKCAE&message_ts=1726655259.562219
)

> Thanks Guy. My only comment would be as to whether it is worth considering geography. Most consumers will be interested in particular council areas (will be over a hundred) so I wonder whether the directory and dashboard might warrant some form of grouping into at least the 9 regions e.g. North West. I accept that this is not straight forward as some feeds will cross geographical boundaries. Perhaps they could have area tags that could be filtered to see all feeds in north west. I don't have the answer so only raising to see if you think it should be considered.

if was can add metadata to support this I 💯 agree with Ian that it would really support the directory use cases.

CONS: UK administrative geography is hard to understand for lay people ((who arguably aren't the audience anyway!), hard to make UIs for (mmm, big long select list anyone, or a tinyweeny map with a hundred clickable not accessible bits) and worst of all, changes from time to time, which is a potential future maintenance issue. The absolute ideal ui would be a postcode search but this won't be feasible on the present scope so realistically I think we would indeed be looking at the traditional very long select box!

**Comment by MikeThacker1** [comment]
I don't think our main audience is lay people and commercial developers, councils and other public sector bodies may be interested in filtering by geographical area (e.g. region).

Initially we won't have many feeds so this can be logged as a possible future enhancement. To keep it quite generic, we could have a tagging function allowing any (or predefined) text "tag" terms to be added (by the publisher?) - perhaps prompted with terms that already exist. The list could then be filtered by tag (e.g. graphical area, or service area such as Adult Services).

If we ever do need postcodes, LA geographies and associated relationships, the LGA's [LG Inform Plus API](https://developertools.esd.org.uk/api) might help.

**Comment by gjhltn** [comment]
Given our present brief I'm reluctant to build in dependency on third party services - and postcode search will be overkill until there are a very large number of services to comb through - so happy to park that idea.

BUT I do think the idea of allowing some regional organisation is very much worth considering - Id like to propose that for now adding a 'region' column - London, North East, North West, Yorkshire, East Midlands, West Midlands, South East, East of England and South West - do we need to add Scotland and Wales? - and allowing sorting on region would feel like a reasonable first cut at this - if and when we have completed the minimum scope already promised.

**Comment by gjhltn** [comment]
We've decided not to do this I think.
