### ISSUE TITLE
Handling multiple API versions in docs

### ISSUE THREAD

**Issue by gjhltn** [tpximpact/mhclg-oruk#19]
I make no bones about it, the proposed solution here was v much inspired by the way Next.js handles a similar problem. 

My plan would be - all of this a nice to have, not an essential or a promise! - to provide on-page UI to switch between documentation versions. 

ie much like the top left of https://nextjs.org/docs/13

![IMG_5557](https://github.com/user-attachments/assets/7f0d8ced-701b-4e26-b9c7-0612bc7cf28a)

(It might for some use cases be valuable to be able to view both at the same time side by side... but this doesn't really scale to more than two versions of the standard, so I don't think it is the most sustainable option for the future - I feel the option above - a toggle - is better in the case where we have multiple future versions of the standard to compare)

**Comment by MikeThacker1** [comment]
Guy, I'm happy to defer to you and Laura on aspects of the UI. Just two points:

1. we need to be very clear what version we're dealing with and how to switch. The latest version should be the default although many may reference the initial version at first
2. this applies not just to the API but to the HSDS structure and many aspects of the guidance

**Comment by gjhltn** [comment]
Dine
