### ISSUE TITLE
Indicate when the form is submitted and stop multiple submissions

### ISSUE THREAD

**Issue by MikeThacker1** [tpximpact/mhclg-oruk#32]
On pressing enter from the URL field, there is no indication that anything is happening until the results page comes up. The black/white swap on hover over the “CHECK” button helps. Might we have something to indicate a check is underway and maybe a pause during which the check submit is disabled to stop the user running it multiple times?

**Comment by gjhltn** [comment]
Hopefully done now. Button greys out and is disabled. Reopen if you dont like it!
