### ISSUE TITLE
Example feeds not prominent enough

### ISSUE THREAD

**Issue by MikeThacker1** [tpximpact/mhclg-oruk#33]
Might we provide small sample feeds (for V3 and possibly v1) that will pass that can be referenced under “e.g. …”

This could be a big job. If so, don't do.

**Comment by gjhltn** [comment]
Is done. It's already in the page. 

Should we be changing  this issue to be "example feeds not prominent enough?"

**Comment by MikeThacker1** [comment]
> Is done. It's already in the page.
Where? I can't see it on [this page](https://openreferraluk.netlify.app/developers/validator)?
https://example.com/my-oruk-feed just gives errors (as I would expect).

Ahh if we're saying that the URLs given in the examples of [Pass](https://openreferraluk.netlify.app/developers/validator/edcf9d03-47dd-4c46-833b-e9831d505c72?uri=https://oruk-api-2a920f51d6bb.herokuapp.com/api/mock), [Pass - but with warnings](https://openreferraluk.netlify.app/developers/validator/4c305b8e-204e-4211-8670-9fd0d93b55f3?uri=https://oruk-api-2a920f51d6bb.herokuapp.com/api/mock/warn) and [Fail](https://openreferraluk.netlify.app/developers/validator/886de765-9e51-45e9-b4ea-5c69e4e86877?uri=https://oruk-api-2a920f51d6bb.herokuapp.com/api/mock/fail),  then YES, I would suggest making that more obvious.

**Comment by gjhltn** [comment]
Yes it's those links.It used to be more of a feature but I was persuaded it was too much in the way. TBH I kind of remain persuaded! But easy to change if we need to for sureOn 15 Nov 2024, at 12:46, MikeThacker1 ***@***.***> wrote:﻿

Is done. It's already in the page.

Where? I can't see it on this page?
https://example.com/my-oruk-feed just gives errors (as I would expect).
Ahh if we're saying that the URLs given in the examples of Pass, Pass - but with warnings and Fail,  then YES, I would suggest making that more obvious.

**Comment by MikeThacker1** [comment]
This is just my view. If Guy's is different, maybe we should leave it for external user testing to see if otehrs have the same issue as Mike.
