### ISSUE TITLE
Agree dashboard naming. 

### ISSUE THREAD

**Issue by MikeThacker1** [tpximpact/mhclg-oruk#35]
The front page menu says “Dashboard”, the page title is “Open Referral UK availability monitor”.

**Comment by gjhltn** [comment]
The front page menu is placeholder. 

However: we do need to change this in the menuing....

**Comment by LauraTPX** [comment]
Resolved

**Comment by gjhltn** [comment]
![IMG_6479](https://github.com/user-attachments/assets/4a6fc265-569a-4eda-899e-f6a037d154d3)
