### ISSUE TITLE
Standardise and improve "Last tested" time and date

### ISSUE THREAD

**Issue by MikeThacker1** [tpximpact/mhclg-oruk#37]
“Last tested” shows as “08/6/24, 6:01 PM”. Have consistent zero filling of day and month (dd/mm/yy or d/m/yy). I hate not using the 24 hour clock but fear that is GDS style. If so, must “PM” be capitalised?

**Comment by gjhltn** [comment]
Closed by https://github.com/tpximpact/mhclg-oruk/commit/7994809ad558ed481ff097938443c35a7ca1c839
