### ISSUE TITLE
Better explain the "Service" link

### ISSUE THREAD

**Issue by MikeThacker1** [tpximpact/mhclg-oruk#39]
What does the “Service” link go to? When the text is no longer “example.com”, how will the user know it’s an example?

**Comment by gjhltn** [comment]
It's not an example, it's the actual feed as supplied by the client, the  thing we are testing!

This raises a really important general issue tbh what do we call... uh.... the thing that oruk providers provide? Variously internally we call these feeds or services... is there a better

**Comment by gjhltn** [comment]
But it's a fair point that this needs a label. Am canvassing Laura on this as we speak....

**Comment by gjhltn** [comment]
Laura has solved it. It's labelled data feed. Re open the issue if this doesn't fix it for you! 😀
