### ISSUE TITLE
Clarify what Validator functional requirement "may provide results" means

### ISSUE THREAD

**Issue by MikeThacker1** [tpximpact/mhclg-oruk#4]
Clarify what [Validator functional requirement "2.2 h)](https://github.com/tpximpact/mhclg-oruk/wiki/Requirements#h-colorgoldenrodnormalsizetextsf--may--may-provide-results)  may provide results" means

**Comment by gjhltn** [comment]
Yes agree. Have clarified the wording in [f709f7f](https://github.com/tpximpact/mhclg-oruk/wiki/Requirements/f709f7f2dc6d34cecadd7f314956d8bf3d64d32e)

**Comment by MikeThacker1** [comment]
That's clear now.
